package com.project.model;

// Generated 10-Dec-2015 21:04:20 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Livre generated by hbm2java
 */
@Entity
@Table(name = "LIVRE")
public class Livre implements java.io.Serializable {

	private long isbn;
	private String titre;
	private String nomauteur;
	private int nbrdispo;
	private Set<Pret> prets = new HashSet<Pret>(0);

	public Livre() {
	}

	public Livre(long isbn, String titre, int nbrdispo) {
		this.isbn = isbn;
		this.titre = titre;
		this.nbrdispo = nbrdispo;
	}

	public Livre(long isbn, String titre, String nomauteur, int nbrdispo,
			Set<Pret> prets) {
		this.isbn = isbn;
		this.titre = titre;
		this.nomauteur = nomauteur;
		this.nbrdispo = nbrdispo;
		this.prets = prets;
	}

	@Id
	@Column(name = "ISBN", unique = true, nullable = false, precision = 13, scale = 0)
	public long getIsbn() {
		return this.isbn;
	}

	public void setIsbn(long isbn) {
		this.isbn = isbn;
	}

	@Column(name = "TITRE", nullable = false, length = 60)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "NOMAUTEUR", length = 60)
	public String getNomauteur() {
		return this.nomauteur;
	}

	public void setNomauteur(String nomauteur) {
		this.nomauteur = nomauteur;
	}

	@Column(name = "NBRDISPO", nullable = false, precision = 5, scale = 0)
	public int getNbrdispo() {
		return this.nbrdispo;
	}

	public void setNbrdispo(int nbrdispo) {
		this.nbrdispo = nbrdispo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "livre")
	public Set<Pret> getPrets() {
		return this.prets;
	}

	public void setPrets(Set<Pret> prets) {
		this.prets = prets;
	}

}
