package com.project.model;

// Generated 10-Dec-2015 21:04:20 by Hibernate Tools 4.0.0

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pret generated by hbm2java
 */
@Entity
@Table(name = "PRET")
public class Pret implements java.io.Serializable {

	private PretId id;
	private Membre membre;
	private Livre livre;
	private Date datepret;

	public Pret() {
	}

	public Pret(PretId id, Membre membre, Livre livre, Date datepret) {
		this.id = id;
		this.membre = membre;
		this.livre = livre;
		this.datepret = datepret;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "isbn", column = @Column(name = "ISBN", nullable = false, precision = 13, scale = 0)),
			@AttributeOverride(name = "cin", column = @Column(name = "CIN", nullable = false, precision = 8, scale = 0)) })
	public PretId getId() {
		return this.id;
	}

	public void setId(PretId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CIN", nullable = false, insertable = false, updatable = false)
	public Membre getMembre() {
		return this.membre;
	}

	public void setMembre(Membre membre) {
		this.membre = membre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ISBN", nullable = false, insertable = false, updatable = false)
	public Livre getLivre() {
		return this.livre;
	}

	public void setLivre(Livre livre) {
		this.livre = livre;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATEPRET", nullable = false, length = 7)
	public Date getDatepret() {
		return this.datepret;
	}

	public void setDatepret(Date datepret) {
		this.datepret = datepret;
	}

}
