package com.project.model;

// Generated 10-Dec-2015 21:04:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PretId generated by hbm2java
 */
@Embeddable
public class PretId implements java.io.Serializable {

	private long isbn;
	private int cin;

	public PretId() {
	}

	public PretId(long isbn, int cin) {
		this.isbn = isbn;
		this.cin = cin;
	}

	@Column(name = "ISBN", nullable = false, precision = 13, scale = 0)
	public long getIsbn() {
		return this.isbn;
	}

	public void setIsbn(long isbn) {
		this.isbn = isbn;
	}

	@Column(name = "CIN", nullable = false, precision = 8, scale = 0)
	public int getCin() {
		return this.cin;
	}

	public void setCin(int cin) {
		this.cin = cin;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PretId))
			return false;
		PretId castOther = (PretId) other;

		return (this.getIsbn() == castOther.getIsbn())
				&& (this.getCin() == castOther.getCin());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getIsbn();
		result = 37 * result + this.getCin();
		return result;
	}

}
