package com.project.model;

// Generated 10-Dec-2015 21:04:20 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Utilisateur generated by hbm2java
 */
@Entity
@Table(name = "UTILISATEUR")
public class Utilisateur implements java.io.Serializable {

	private String login;
	private String password;
	private byte nbrlim;
	private byte dureelim;
	private String type;

	public Utilisateur() 
	{
		nbrlim = 2;
		dureelim = 15;
	}

	public Utilisateur(String login, String password, byte nbrlim,
			byte dureelim, String type) {
		this.login = login;
		this.password = password;
		this.nbrlim = nbrlim;
		this.dureelim = dureelim;
		this.type = type;
	}

	@Id
	@Column(name = "LOGIN", unique = true, nullable = false, length = 60)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "PASSWORD", nullable = false, length = 60)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "NBRLIM", nullable = false, precision = 2, scale = 0)
	public byte getNbrlim() {
		return this.nbrlim;
	}

	public void setNbrlim(byte nbrlim) {
		this.nbrlim = nbrlim;
	}

	@Column(name = "DUREELIM", nullable = false, precision = 2, scale = 0)
	public byte getDureelim() {
		return this.dureelim;
	}

	public void setDureelim(byte dureelim) {
		this.dureelim = dureelim;
	}

	@Column(name = "TYPE", nullable = false, length = 60)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
